linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true

  gofmt:
    simplify: true

  goimports:
    local-prefixes: z

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - goconst
    - misspell
    - unconvert
    - unparam
    - gocyclo
    - dupl

  disable:
    - golint  # deprecated

run:
  timeout: 5m
  skip-dirs:
    - vendor

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

output:
  sort-results: true
